import { Icon } from './Icons'

const steps = [
  { number: '01', title: 'See', icon: 'scan', copy: 'Recognize the object and the visual cues that make it distinct.', accent: 'teal' },
  { number: '02', title: 'Understand', icon: 'eye', copy: 'Assess visible condition without pretending to know what is hidden.', accent: 'violet' },
  { number: '03', title: 'Decompose', icon: 'layers', copy: 'Map materials and components that could keep their value.', accent: 'lime' },
  { number: '04', title: 'Reimagine', icon: 'sparkles', copy: 'Generate realistic repair, reuse, repurpose, donate, and recover ideas.', accent: 'amber' },
  { number: '05', title: 'Compare', icon: 'chart', copy: 'Score the trade-offs across cost, effort, time, impact, and usefulness.', accent: 'indigo' },
  { number: '06', title: 'Extend Life', icon: 'leaf', copy: 'Recommend the clearest next action and turn it into steps.', accent: 'teal' },
]

export function HowItWorksPage({ navigate }) {
  return <div className="how-page page-section"><div className="container how-container"><div className="how-hero"><div><div className="section-kicker">THE OBJECTDNA PIPELINE</div><h1>Waste isn’t the end.<br /><em>It is a question.</em></h1><p>ObjectDNA gives everyday objects a moment of consideration before they leave the loop.</p></div><div className="how-hero-visual"><div className="how-orbit" /><div className="how-center"><Icon name="leaf" size={33} /><span>possibility<br />engine</span></div><span className="orbit-label label-scan">see</span><span className="orbit-label label-understand">compare</span><span className="orbit-label label-act">extend</span></div></div><div className="flow-banner"><span>SEE</span><Icon name="arrow" size={18} /><span>UNDERSTAND</span><Icon name="arrow" size={18} /><span>REIMAGINE</span><Icon name="arrow" size={18} /><span>EXTEND LIFE</span></div><section className="step-section"><div className="section-heading-row"><div><div className="section-kicker">THE LOOP</div><h2>Simple for people.<br /><em>Useful for objects.</em></h2></div><p className="section-side-copy">A calm, guided path from “I don’t know” to “I know what to do next.”</p></div><div className="how-step-grid">{steps.map((step) => <div className={`how-step tone-${step.accent}`} key={step.number}><span className="how-step-number">{step.number}</span><div className="how-step-icon"><Icon name={step.icon} size={23} /></div><h3>{step.title}</h3><p>{step.copy}</p><span className="step-underline" /></div>)}</div></section><section className="principles-section"><div className="principle-quote"><Icon name="quote" size={28} /><h2>Before disposal,<br /><em>explore potential.</em></h2><p>Repair and reuse are not just end-of-life choices. They are a better first question when something still has value.</p></div><div className="principle-list"><Principle icon="shield" title="Visible facts only" copy="The assistant describes what can be seen, not hidden internal condition." /><Principle icon="chart" title="Explainable ranking" copy="Life-Path Score shows the factors behind each recommendation." /><Principle icon="leaf" title="Estimates, not promises" copy="Environmental numbers are clearly labeled as AI-generated estimates." /><Principle icon="users" title="Made for real people" copy="Households, students, institutions, repairers, makers, and communities can all use it." /></div></section><div className="how-cta"><div><span className="section-kicker">READY TO LOOK CLOSER?</span><h2>Give an object<br /><em>another answer.</em></h2></div><button className="button button-dark" onClick={() => navigate('/analyze')}>Analyze an object <Icon name="arrow" size={16} /></button></div></div></div>
}

function Principle({ icon, title, copy }) {
  return <div className="principle-row"><span className="principle-icon"><Icon name={icon} size={19} /></span><div><strong>{title}</strong><p>{copy}</p></div></div>
}
